s2_arm:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  arm_joint1_controller:
    type: position_controller/JointPositionController
    joint: arm_joint1
    pid: {p: 0.0, i: 0.0, d: 0.0, i_clamp: 1}
  arm_joint2_controller:
    type: position_controller/JointPositionController
    joint: arm_joint2
    pid: {p: 0.0, i: 0.0, d: 0.0, i_clamp: 1}